"""Document jobs (user decision 2026-10-08): own deliverables may be re-generated (old version kept), other files are
never overwritten; unchecked items do not stop the job; the security review follows the planner's judgment."""
import hashlib
import json
import tempfile
import time
import unittest
from pathlib import Path

import document_tools
from team_adapters import ADAPTERS
from team_config import default_config
from team_engine import Engine
from team_store import Store


class OwnOutputTest(unittest.TestCase):
    def setUp(self):
        self.folder = tempfile.TemporaryDirectory()
        self.addCleanup(self.folder.cleanup)
        self.root = Path(self.folder.name).resolve()
        self.file = self.root / 'guide.pdf'
        self.file.write_bytes(b'%PDF-1.4 first')

    def record(self, job='job1'):
        digest = hashlib.sha256(self.file.read_bytes()).hexdigest()
        (self.root / f'.saikuru-output-{job}.json').write_text(json.dumps([{'path': 'guide.pdf', 'sha256': digest}]), encoding='utf-8')

    def test_own_deliverable_can_be_replaced_and_old_is_kept(self):
        self.record()
        self.assertTrue(document_tools._own_output(self.root, self.file, 'job1'))
        kept = document_tools._set_aside(self.root, self.file)
        self.assertFalse(self.file.exists())
        self.assertEqual((self.root / kept).read_bytes(), b'%PDF-1.4 first')
        self.assertTrue(kept.startswith('.saikuru-versions'))

    def test_other_files_are_never_overwritten(self):
        with self.assertRaises(ValueError):
            document_tools._own_output(self.root, self.file, 'job1')  # not generated by this job
        self.record('other-job')
        with self.assertRaises(ValueError):
            document_tools._own_output(self.root, self.file, 'job1')  # generated by a different job
        self.record()
        self.file.write_bytes(b'%PDF-1.4 changed by a person')
        with self.assertRaises(ValueError):
            document_tools._own_output(self.root, self.file, 'job1')  # changed after generation

    def test_new_path_is_not_a_replacement(self):
        self.assertFalse(document_tools._own_output(self.root, self.root / 'new.pdf', 'job1'))

    def test_upper_case_extension_is_accepted(self):
        path = document_tools.output_path(self.root, 'Guide.PDF')
        self.assertEqual(path.suffix, '.pdf')
        (self.root / 'NOTE.MD').write_text('本文', encoding='utf-8')
        result = document_tools.document_operation(self.root, 'read_document', {'path': 'NOTE.MD'}, False)
        self.assertEqual(result['content'], '本文')


PLAN = {'summary': '計画', 'tasks': [{'title': '確認', 'instruction': '確認する', 'role': 'researcher'}],
        'security_review_required': False}
HANDOFF = {'status': 'handoff', 'summary': '見た目の確認は未実施', 'checks': ['未確認：見た目'], 'question': ''}
DONE = {'status': 'done', 'summary': '完了', 'checks': ['確認：本文'], 'question': ''}


class Fixture:
    def run(self, ctx, prompt, schema):
        return PLAN if ctx.task['role'] == 'planner' else HANDOFF if ctx.task['role'] == 'researcher' else DONE


class DocumentJobTest(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.store = Store(self.temp.name)
        config = default_config()
        config['document_review_relaxed'] = True
        config['approved_roots'] = [self.temp.name]
        self.engine = Engine(self.store, config, {'codex': ['fixture'], 'claude': ['fixture']}, 'http://127.0.0.1:1')
        self.saved = ADAPTERS.copy()
        ADAPTERS.update(codex=Fixture, claude=Fixture)

    def tearDown(self):
        self.engine.shutdown.set()
        deadline = time.time() + 3
        while self.engine.active and time.time() < deadline:
            time.sleep(.01)
        ADAPTERS.update(self.saved)
        self.engine.handoff.close()
        self.store.db.close()
        self.temp.cleanup()

    def test_unchecked_items_do_not_stop_and_no_forced_security_review(self):
        job = self.engine.create_job('資料', '内部資料を作る', self.temp.name, True,
                                     document_source=self.temp.name, document_format='md')
        deadline = time.time() + 6
        while self.store.get(job['id'])['status'] not in ('awaiting_acceptance', 'blocked', 'failed') and time.time() < deadline:
            self.engine.tick()
            time.sleep(.01)
        tasks = self.store.all('task')
        researcher = next(t for t in tasks if t['role'] == 'researcher')
        self.assertEqual(researcher['status'], 'handed_off')
        self.assertFalse(any(t.get('agent_name') == 'common-security-reviewer' for t in tasks))
        self.assertEqual(self.store.get(job['id'])['status'], 'awaiting_acceptance')
        completion = next(a for a in self.store.all('approval') if a['kind'] == 'completion')
        self.assertEqual(completion['payload']['pending_items'][0]['title'], '確認')

    def test_report_with_questions_is_treated_as_blocked(self):
        question = {'id': 'q1', 'text': 'どちらの形式にしますか', 'options': [
            {'id': 'a', 'label': 'PDF', 'input_required': False, 'input_label': ''}]}
        result = {'status': 'done', 'summary': '形式の確認が必要', 'checks': [], 'question': '', 'questions': [question]}
        self.engine._validate({'role': 'reviewer', 'job_id': 'none'}, result)
        self.assertEqual(result['status'], 'blocked')


class ReviewFindingsTest(DocumentJobTest):
    def test_review_findings_go_to_acceptance_instead_of_stopping(self):
        findings = {'status': 'needs_changes', 'summary': '重大度：低。案内文の表現を分けて書くとよい。', 'checks': ['確認：本文'], 'question': ''}
        class FindingFixture:
            def run(s, ctx, prompt, schema):
                return PLAN if ctx.task['role'] == 'planner' else findings if ctx.task['role'] == 'reviewer' else DONE
        ADAPTERS.update(codex=FindingFixture, claude=FindingFixture)
        job = self.engine.create_job('資料', '内部資料を作る', self.temp.name, True,
                                     document_source=self.temp.name, document_format='md')
        deadline = time.time() + 6
        while self.store.get(job['id'])['status'] not in ('awaiting_acceptance', 'blocked', 'failed') and time.time() < deadline:
            self.engine.tick()
            time.sleep(.01)
        self.assertEqual(self.store.get(job['id'])['status'], 'awaiting_acceptance')
        self.assertFalse(any(t['title'] == 'レビュー指摘を修正する' for t in self.store.all('task')))
        completion = next(a for a in self.store.all('approval') if a['kind'] == 'completion')
        self.assertIn('案内文の表現', completion['payload']['review_findings'][0]['summary'])


class AcceptWithoutFixTest(ReviewFindingsTest):
    def test_stopped_document_job_moves_to_acceptance(self):
        self.test_review_findings_go_to_acceptance_instead_of_stopping()
        job = self.store.all('job')[0]
        reviewer = [t for t in self.store.all('task') if t['role'] == 'reviewer'][-1]
        # A fix requested from the board failed (e.g. usage limit) and a re-review is still waiting.
        fix = self.engine.new_task(job, '利用者指定のレビュー指摘を修正する', '直す', 'builder', reviewer['id'], 1)
        self.store.update(fix['id'], status='failed')
        recheck = self.engine.new_task(job, '別担当が成果と検証を確認する', '確認', 'reviewer', fix['id'], 1)
        self.store.update(job['id'], status='failed')
        deadline = time.time() + 3
        while self.engine.active and time.time() < deadline:  # the reviewer thread finishes after reporting
            time.sleep(.01)
        self.engine.accept_without_fix(job['id'])
        self.assertEqual(self.store.get(job['id'])['status'], 'awaiting_acceptance')
        self.assertEqual(self.store.get(fix['id'])['status'], 'cancelled')
        self.assertEqual(self.store.get(recheck['id'])['status'], 'cancelled')
        pending = [a for a in self.store.all('approval') if a['status'] == 'pending']
        self.assertEqual([a['kind'] for a in pending], ['completion'])
        self.assertTrue(pending[0]['payload']['review_findings'])

    def test_only_document_jobs(self):
        job = self.engine.create_job('開発', '作る', self.temp.name, True)
        self.store.update(job['id'], status='failed')
        with self.assertRaises(ValueError):
            self.engine.accept_without_fix(job['id'])


if __name__ == '__main__':
    unittest.main()
